import Head from "next/head";
import React from "react";
import PageLayout from "../../components/PageLayout";
import TextEditor from "../../components/TextEditor";
import { FlexColCenteredX } from "@/components/styled-global-components";

export default function EditorPage() {
  return (
    <>
      <Head>
        <title>Dev Playground - EditorTest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <FlexColCenteredX className="h-[100vh] mt-6">
          <TextEditor />
        </FlexColCenteredX>
      </PageLayout>
    </>
  );
}
